# Generated by Django 3.2.11 on 2022-02-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('contacto', '0003_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
