# Generated by Django 3.2.11 on 2022-02-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticiasindexpage_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiasindexpage',
            name='imagen',
        ),
    ]
