# Generated by Django 3.2.11 on 2022-02-23 08:05

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_noticia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'noticia', 'verbose_name_plural': 'noticias'},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='link',
        ),
        migrations.AddField(
            model_name='noticia',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
