# Generated by Django 3.2.11 on 2022-02-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('noticias', '0007_noticia_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiaspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='noticiaspagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='noticiaspagegalleryimage',
            name='page',
        ),
        migrations.DeleteModel(
            name='NoticiasIndexPage',
        ),
        migrations.DeleteModel(
            name='NoticiasPage',
        ),
        migrations.DeleteModel(
            name='NoticiasPageGalleryImage',
        ),
    ]
