# Generated by Django 3.2.11 on 2022-02-21 19:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('subtitle', models.CharField(blank=True, max_length=40)),
                ('link', models.URLField()),
                ('rank', models.IntegerField()),
                ('imagen', models.URLField()),
                ('urlAuthor', models.URLField()),
                ('data', models.CharField(blank=True, max_length=250)),
                ('price', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LibrosIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduccion', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
