# Generated by Django 3.2.11 on 2022-02-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='author',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
