# Generated by Django 3.2.11 on 2022-02-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_libro_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='synopsis',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
