# Generated by Django 3.2.11 on 2022-02-24 12:47

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220222_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viajespage',
            name='fecha',
        ),
        migrations.AddField(
            model_name='viajespage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.BlogCategory'),
        ),
        migrations.AddField(
            model_name='viajespage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Post'),
        ),
        migrations.AddField(
            model_name='viajespage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='viajespage',
            name='lugar',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
