# Generated by Django 3.2.11 on 2022-02-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20220224_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajespage',
            name='date',
            field=models.DateField(verbose_name='Fecha Viaje'),
        ),
        migrations.AlterField(
            model_name='viajespage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, verbose_name='Introducción'),
        ),
        migrations.AlterField(
            model_name='viajespage',
            name='lugar',
            field=models.CharField(max_length=30),
        ),
    ]
