# Generated by Django 3.2.11 on 2022-02-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20220224_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajespage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Viaje'),
        ),
        migrations.AlterField(
            model_name='viajespage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Introducción'),
        ),
    ]
