# Generated by Django 3.2.11 on 2022-02-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_musicapage'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajespage',
            name='coord',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
