# Generated by Django 3.2.11 on 2022-02-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_viajespage_coord'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajespage',
            name='imagen',
            field=models.URLField(blank=True),
        ),
    ]
