# Generated by Django 3.2.11 on 2022-03-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_pelipage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelipage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='pelipage',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='pelipage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='pelipage',
            name='titulo',
        ),
    ]
