# Generated by Django 3.2.11 on 2022-03-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20220302_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelipage',
            name='ids',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
