# Generated by Django 3.2.11 on 2022-02-01 08:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('pelis', '0002_alter_pelicula_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PelisPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduccion', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
